### ISSUE TITLE
Export to Draw.io not working

### ISSUE THREAD

**Issue by tibernardinelli** [awslabs/aws-perspective#35]
**Describe the bug**
When you click in export to draw io a new tab is open redirecting to "Network error" address

**To Reproduce**
1. In a drawing
2. Click on 'drawio'

**Expected behavior**
Open Draw.io with your architecture

**Screenshots**
![Screen Shot 2020-09-26 at 7 09 28 PM](https://user-images.githubusercontent.com/485908/94351114-dad64000-002b-11eb-9fea-a78ef926126a.png)

**Browser (please complete the following information):**

- Name chrome

**Additional context**

**Comment by thebutler12** [comment]
Hi, could you please provide an example of the diagram you are trying to export? Don't forget to remove any account Ids from the bounding boxes.

**Comment by agrondemiraj** [comment]
Same is not working for me. Attached screenshot.
![export-to drawio](https://user-images.githubusercontent.com/66549050/94485708-05b8c380-01e7-11eb-9cec-3571323dd260.png)

**Comment by thebutler12** [comment]
Sorry to hear this, could you provide details about the diagram you had drawn in Perspective that you were trying to export to Drawio please?

**Comment by Mic-U** [comment]
Hello.
I could replicated the same issue when I draw NO diagrams.
Then, I saw the following error on developer tools in Google Chrome.
It seems invalid URL.

```
xhr.js:172 POST https://msmkergp03.execute-api.us-east-1.amazonaws.com/Prod//resources net::ERR_FAILED
```

When I draw any diagrams on Perspective, I couldn't replicate.

**Comment by thebutler12** [comment]
Thanks for this info, so it appears the bug is caused by trying export an empty canvas to DrawIO. Are you any other issues when trying to export an architecture diagram? If so, please provide information about the diagram you are trying to export (a screenshot from Perspective would be great)

**Comment by jeff-s-burns** [comment]
I am receiving the same error when exporting Architecture Diagram using Draw.io (error:Network Error).  Very simple Arch Diagram (5 EC2 instances)

![image](https://user-images.githubusercontent.com/71841393/115040099-11c45400-9e9f-11eb-8362-4949b148259d.png)

**Comment by WH-West** [comment]
I was experiencing this issue in chrome as well, but when I tried in firefox it did successfully export.

**Comment by ankitosh** [comment]
Draw.io Export is not working for me. 
Attached here is SS for reference.
![image](https://user-images.githubusercontent.com/38682280/127286895-f793f427-1d92-49ef-a01f-ced26ff83fcc.png)

**Comment by svozza** [comment]
Are any resources appearing in the side panel?

Regarding draw.io, there is a bug that happens when a diagram has no edges that causes an error on the server side. This has been fixed in v1.1.0, which will be released soon.

**Comment by ankitosh** [comment]
Update : 
1) Increased Draw.io lambda function Ram size from 256 to 512 and timeout from 5 seconds to 15 seconds this resolved export to draw.io.

Still facing below issue
1) Yes, resources are coming up
![image](https://user-images.githubusercontent.com/38682280/127437483-7cee5b38-41e2-4386-a34a-b28eb29864b2.png)
But when select 2 resources
For. Eg. when selected 1 VPC it works fine, if select Subnet within that VPC page turns blank.
![image](https://user-images.githubusercontent.com/38682280/127437483-7cee5b38-41e2-4386-a34a-b28eb29864b2.png)
2) Discovery Process is not ending.  I changed the Fargate Scheduled task for from every 15 min to every 4 hours, still Discovery Process is not ending. 

Regards
